### ISSUE TITLE
SDK does not works with python 3.8

### ISSUE THREAD

**Issue by jskrnbindra** [cashfree/cashfree-sdk-python#7]
Either the [readme](https://github.com/cashfree/cashfree-sdk-python/blob/master/README.md#installing) must be updated or the SDK must be made compatible with python >= 3.8 as well. 

##### Expected behaviour:
It should just work.

##### Actual behaviour:
```
Exception: AttributeError: module 'time' has no attribute 'clock'
Stack:   File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py", line 310, in _handle__invocation_request
    call_result = await self._loop.run_in_executor(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py", line 431, in __run_sync_func
    return func(**params)
  File "/home/site/wwwroot/paymentLinkCallback/__init__.py", line 172, in main
    send_cashgram(from_user, to_user, receipt)
  File "/home/site/wwwroot/paymentLinkCallback/__init__.py", line 140, in send_cashgram
    ref_id = create_cashgram(to_user, receipt)
  File "/home/site/wwwroot/paymentLinkCallback/__init__.py", line 119, in create_cashgram
    created_cashgram = Cashgram.create_cashgram(
  File "/home/site/wwwroot/.python_packages/lib/site-packages/cashfree_sdk/payouts/__authorize_creds.py", line 96, in authenticate_gen_token
    authenticate()
  File "/home/site/wwwroot/.python_packages/lib/site-packages/cashfree_sdk/payouts/__authorize_creds.py", line 35, in authenticate
    generate_signature()
  File "/home/site/wwwroot/.python_packages/lib/site-packages/cashfree_sdk/payouts/__authorize_creds.py", line 72, in generate_signature
    signature = encrypter.encrypt(encode_data.encode())
  File "/home/site/wwwroot/.python_packages/lib/site-packages/Crypto/Cipher/PKCS1_OAEP.py", line 152, in encrypt
    ros = randFunc(hLen)
  File "/home/site/wwwroot/.python_packages/lib/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 202, in read
    return self._singleton.read(bytes)
  File "/home/site/wwwroot/.python_packages/lib/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 178, in read
    return _UserFriendlyRNG.read(self, bytes)
  File "/home/site/wwwroot/.python_packages/lib/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 129, in read
    self._ec.collect()
  File "/home/site/wwwroot/.python_packages/lib/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 77, in collect
    t = time.clock()
```

**Comment by ankur-cashfree** [comment]
time.clock has been removed from Python 3.8, and there is indirect dependency used by  pycrypto package which is the immediate cause of this error

Can you post the output of python3 -m pycrypto?

**Comment by jskrnbindra** [comment]
`pycrypto` is surely the cause. I faced this while I was running in python3.8 runtime and we've switched to python3.7 for now. Won't be able to show output of `python3 -m pycrypto` as this was running in serverless.
